apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-client-secret
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-oke
  target:
    name: argocd-oidc-client-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        clientSecret: "{{ .clientSecret }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: ARGOCD_OIDC_CLIENT_SECRET
