apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-oke-signalforge
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com/api
      auth:
        tokenAuthCredentials:
          accessToken:
            name: infisical-oke-signalforge-auth
            namespace: external-secrets
            key: accessToken
      secretsScope:
        projectSlug: canepro-secrets
        environmentSlug: prod
        secretsPath: /platform/oke/signalforge
        recursive: false
        expandSecretReferences: false
