apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-smtp-credentials
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-oke-monitoring
  target:
    name: grafana-smtp-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: GRAFANA_SMTP_PASSWORD
    - secretKey: user
      remoteRef:
        key: GRAFANA_SMTP_USER
    - secretKey: from_address
      remoteRef:
        key: GRAFANA_SMTP_FROM_ADDRESS
    - secretKey: to_address
      remoteRef:
        key: GRAFANA_SMTP_TO_ADDRESS
