apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-github
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: jenkins-github
    creationPolicy: Owner
    template:
      data:
        username: "Canepro"
        password: "{{ .token }}"
      metadata:
        labels:
          jenkins.io/credentials-type: usernamePassword
        annotations:
          jenkins.io/credentials-id: "github-token"
          jenkins.io/credentials-description: "GitHub Personal Access Token for PR validation and API access"
  data:
    - secretKey: token
      remoteRef:
        key: jenkins-github-token
