apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-admin-credentials
  namespace: jenkins
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-oke-jenkins
  target:
    name: jenkins-admin-credentials
    creationPolicy: Owner
    template:
      data:
        admin-user: "{{ .username }}"
        admin-password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: JENKINS_ADMIN_USERNAME
    - secretKey: password
      remoteRef:
        key: JENKINS_ADMIN_PASSWORD
