apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-pipelinehealer-bridge-secret
  namespace: jenkins
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault
  target:
    name: pipelinehealer-bridge-secret
    creationPolicy: Owner
    template:
      data:
        text: "{{ .text }}"
      metadata:
        labels:
          jenkins.io/credentials-type: secretText
        annotations:
          jenkins.io/credentials-id: "pipelinehealer-bridge-secret"
          jenkins.io/credentials-description: "PipelineHealer Jenkins bridge shared secret"
  data:
    - secretKey: text
      remoteRef:
        key: jenkins-pipelinehealer-bridge-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-pipelinehealer-bridge-url
  namespace: jenkins
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault
  target:
    name: pipelinehealer-bridge-url
    creationPolicy: Owner
    template:
      data:
        text: "{{ .text }}"
      metadata:
        labels:
          jenkins.io/credentials-type: secretText
        annotations:
          jenkins.io/credentials-id: "pipelinehealer-bridge-url"
          jenkins.io/credentials-description: "PipelineHealer Jenkins bridge webhook URL"
  data:
    - secretKey: text
      remoteRef:
        key: jenkins-pipelinehealer-bridge-url
