apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: observability-auth
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-oke-monitoring
  target:
    name: observability-auth
    creationPolicy: Owner
  data:
    - secretKey: auth
      remoteRef:
        key: OBSERVABILITY_BASIC_AUTH
