apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: canepro-spoke
  namespace: argocd
spec:
  description: "Management for the k8.canepro.me AKS cluster (may be auto-shutdown on a schedule)"
  sourceRepos:
    - "https://github.com/Canepro/rocketchat-k8s.git"
    - "https://rocketchat.github.io/helm-charts"
  destinations:
    - name: k8.canepro.me
      namespace: rocketchat
    - name: k8.canepro.me
      namespace: monitoring
    - name: k8.canepro.me
      namespace: cert-manager
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
