apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  annotations:
    # Owned by app-of-apps `oke-observability-stack` (reduces OutOfSync noise).
    argocd.argoproj.io/tracking-id: oke-observability-stack:argoproj.io/Application:argocd/otel-collector
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.145.0
      helm:
        valueFiles:
          - $values/helm/otel-collector-values.yaml
    - repoURL: https://github.com/Canepro/central-observability-hub-stack.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
